### ISSUE TITLE
Out-of-the-box support for running tasks in parallel

### ISSUE THREAD

**Issue by andywer** [andywer/npm-launch#4]
Might be tricky to visualize with `listr`.

**Comment by uetchy** [comment]
How about bundling a parallel task runner like [npm-run-all](https://github.com/mysticatea/npm-run-all)?

**Comment by andywer** [comment]
Hey @uetchy. Thanks for your feedback.

Yes, I think you could just use npm-run-all right now, but it wouldn't visualize properly which tasks are run.

The problems are right now:
- How to make it work with underlying [Listr](https://github.com/SamVerschueren/listr) package which only supports running things serially
- What should the syntax look like for JSON task files. Two ways possible I can come up with:
  - Special built-in command: `run-p task1 task2`
  - Object with magic keys (kind-of ugly I think): `{ $parallel: ['task1', 'task2'] }`

Feedback is always welcome :)

**Comment by andywer** [comment]
This seems like good news: SamVerschueren/listr#18!
